package au.edu.unsw;


import java.util.ArrayList;
import java.util.List;

//Questions in the form of a arraylist to be used in the exam activity depending on which activity was pressed

public class Topic {
    public String end;
    public List<Question> mQuestions;
    public static Topic getList(String type, int number){
        if (type.equals("introduction")){
            Topic topic =   new Topic();
            ArrayList<Question> list =   new ArrayList<>();
            if (number==1){
                topic.end = "Congratulations, you now know how to describe that feeling you get when you tap your foot to a piece of music. But now think, how boring would it be if all beats were just made up of one duration. It would get boring very quickly! This brings us to our next lesson of rhythm!";
                Question question0=   new Question();
                question0.title = "If you ran faster your heart rate would increase and beat more. Since the time between beats is now shorter would you say the pulse has increased?";
                question0.ansType="text";
                question0.a="Yes";
                question0.b="No";
                question0.ok="a";
                list.add(question0);
                Question question1=   new Question();
                question1.title = "Which pulse is faster this one or this one?";
                question1.ansType="url";
                question1.a="EXG806BLqQw";
                question1.b="2ewJbvsAiLI";
                question1.ok="a";
                list.add(question1);
                Question question2 =   new Question();
                question2.title = "What does a pulse do?";
                question2.ansType="text";
                question2.a="Divides beats into equal duration.";
                question2.b="Tells the performer to breathe at a certain speed.";
                question2.ok="a";
                list.add(question2);
                Question question3 =   new Question();
                question3.title = "If the pulse is faster in one song than another and they are of the same duration which one will have more beats?";
                question3.ansType="text";
                question3.a="The one with the slower pulse";
                question3.b="The one with the faster pulse";
                question3.ok="b";
                list.add(question3);
                topic.mQuestions = list;
            }else if (number==2){
                topic.end = "Great, you’ve started to understand how rhythm works and can create interest in a piece. The next lesson covers pitch and how to understand the way music is written.";
                Question question0=   new Question();
                question0.title = "How many beats in a crotchet? ";
                question0.ansType="text";
                question0.a="1";
                question0.b="2";
                question0.ok="a";
                list.add(question0);
                Question question1 =   new Question();
                question1.title = "How many beats in a minum? ";
                question1.ansType="text";
                question1.a="2";
                question1.b="4";
                question1.ok="a";
                list.add(question1);
                Question question2 =   new Question();
                question2.title = "Which one is a semibreve?";
                question2.ansType="image";
                question2.a="icon_1";
                question2.b="icon_2";
                question2.ok="b";
                list.add(question2);
                Question question3 =   new Question();
                question3.title = "Which one is a minum?";
                question3.ansType="image";
                question3.a="icon_3";
                question3.b="icon_1";
                question3.ok="b";
                list.add(question3);
                Question question4 =   new Question();
                question4.title = "How many crotchets in a semibreve? ";
                question4.ansType="text";
                question4.a="2";
                question4.b="4";
                question4.ok="b";
                list.add(question4);
                topic.mQuestions = list;
            }else if (number==3){
                topic.end = "Great work. Now by itself the lines are actually meaningless unless we have a system to guide it. We’ll touch on that in the next part of the course. ";
                Question question0=   new Question();
                question0.title = "Is this sound high in pitch or low in pitch?";
                question0.titleUrl = "musict4q1";
                question0.ansType="text";
                question0.a="High";
                question0.b="Low";
                question0.ok="a";
                list.add(question0);
                Question question1 =   new Question();
                question1.title = "HIs this sound high in pitch or low in pitch?";
                question1.titleUrl = "musict4q2";
                question1.ansType="text";
                question1.a="Low";
                question1.b="High";
                question1.ok="a";
                list.add(question1);
                Question question2 =   new Question();
                question2.title = "What do we call the system we write on notes on?";
                question2.ansType="text";
                question2.a="Musical Map";
                question2.b="Musical Staff";
                question2.ok="b";
                list.add(question2);
                topic.mQuestions = list;
            }
            return topic;
        }
        if (type.equals("intermediate")){
            Topic topic =   new Topic();
            ArrayList<Question> list =   new ArrayList<>();
            if (number==1){
                topic.end="Time signature as you can see determines how we feel pulses in a music which can be very important especially for an orchestra setting where everyone is playing to the conductor's baton. Time signatures are always written at the beginning of the piece next to the clef symbol which will be our next topic";
                Question question0=   new Question();
                question0.title = "Look at this notation. Is it in ¾ or 4/4 time? ";
                question0.titleUrl = "icon_9";
                question0.ansType="text";
                question0.a="3/4";
                question0.b="4/4";
                question0.ok="a";
                list.add(question0);
                Question question1 =   new Question();
                question1.title = "Look at this notation. Is it in ¾ or 4/4 time? ";
                question1.titleUrl = "icon_10";
                question1.ansType="text";
                question1.a="3/4";
                question1.b="4/4";
                question1.ok="b";
                list.add(question1);
                Question question2 =   new Question();
                question2.title = "Why is it called triple time?";
                question2.ansType="text";
                question2.a="Because the piece is at triple the speed";
                question2.b="Each bar is divided into three beats ";
                question2.ok="b";
                list.add(question2);
                Question question3 =   new Question();
                question3.title = "How many minims are in common time or 4/4 time?";
                question3.ansType="text";
                question3.a="2";
                question3.b="4";
                question3.ok="a";
                list.add(question3);
                Question question4 =   new Question();
                question4.title = "How many crotchets are in triple time or ¾ time?";
                question4.ansType="text";
                question4.a="3";
                question4.b="9";
                question4.ok="a";
                list.add(question4);
                topic.mQuestions = list;
            }else if (number==2){
                topic.end = "Treble clef is usually the one that holds the melody as it is higher in pitch than its counterpart the bass clef which will be explored in the next lesson";
                Question question0=   new Question();
                question0.title = "What note is this? ";
                question0.titleUrl = "icon_11";
                question0.ansType="text";
                question0.a="Line notes";
                question0.b="Space notes";
                question0.ok="b";
                list.add(question0);
                topic.mQuestions = list;
            }else if (number==3){
                topic.end = "As you can hear the bass notes are lower in pitch than the treble clef as the bass clef although they share the same staff. If you struggle to remember the name of the notes try to remember an acronym for the notes for example the gap notes in the bass clef spell out All Cows Eat Grass. ";
                Question question0=   new Question();
                question0.title = "What note is this?";
                question0.titleUrl = "icon_12";
                question0.ansType="text";
                question0.a="Line notes";
                question0.b="Space notes";
                question0.ok="a";
                list.add(question0);
                topic.mQuestions = list;
            }
            return topic;
        }
        if (type.equals("expert")){
            Topic topic =   new Topic();
            ArrayList<Question> list =   new ArrayList<>();
            if (number==1){
                topic.end="As you can imagine shorter notes actually make the music feel faster even though the pulse or tempo of the piece stays the same. This allows composers to manipulate the feeling of a piece while keeping the pulse constant.";
                Question question0=   new Question();
                question0.title = "How many quavers are in a crotchet? ";
                question0.ansType="text";
                question0.a="2";
                question0.b="4";
                question0.ok="a";
                list.add(question0);
                Question question1 =   new Question();
                question1.title = "How many quavers are in a semibreve?";
                question1.ansType="text";
                question1.a="4";
                question1.b="8";
                question1.ok="b";
                list.add(question1);
                Question question2 =   new Question();
                question2.title = "What time signature is this in?";
                question2.ansType="text";
                question2.titleUrl = "icon_22";
                question2.a="3/4";
                question2.b="4/4";
                question2.ok="a";
                list.add(question2);
                Question question3 =   new Question();
                question3.title = "How many semiquavers in a crotchet?";
                question3.ansType="text";
                question3.a="4";
                question3.b="8";
                question3.ok="a";
                list.add(question3);
                Question question4 =   new Question();
                question4.title = "How many beats does a single quaver consist of?";
                question4.ansType="text";
                question4.a="1/2";
                question4.b="1";
                question4.ok="a";
                list.add(question4);
                topic.mQuestions = list;
            }else if (number==2){
                topic.end = "You might have realised Db is the same thing as C#. So you might ask, what is the difference between writing these two things? Although it is beyond our scope, it is to do with key signatures";
                Question question0=   new Question();
                question0.title = "What note would G# be on the keyboard?";
                question0.ansType="text";
                question0.titleUrl="icon_23";
                question0.a="Red";
                question0.b="Blue";
                question0.ok="a";
                list.add(question0);
                Question question1=   new Question();
                question1.title = "What note would D# be on the keyboard?";
                question1.ansType="text";
                question1.a="Black note left to D";
                question1.b="Black note right to D";
                question1.ok="b";
                list.add(question1);
                Question question2=   new Question();
                question2.title = "What note would D♭ be on the keyboard?";
                question2.ansType="text";
                question2.titleUrl="icon_24";
                question2.a="Red";
                question2.b="Blue";
                question2.ok="a";
                list.add(question2);
                Question question3=   new Question();
                question3.title = "What note would A♭ be on the keyboard?";
                question3.ansType="text";
                question3.a="Black note left to A";
                question3.b="Black note right to A";
                question3.ok="a";
                list.add(question3);
                Question question4=   new Question();
                question4.title = "What note would B♭ be on the keyboard?";
                question4.ansType="text";
                question4.titleUrl="icon_25";
                question4.a="Red";
                question4.b="Blue";
                question4.ok="a";
                list.add(question4);
                Question question5=   new Question();
                question5.title = "Which of the following is G♭?";
                question5.ansType="image";
                question5.a="icon_26";
                question5.b="icon_27";
                question5.ok="b";
                list.add(question5);
                topic.mQuestions = list;
            }else if (number==3){
                topic.end = "You’ve completed this course and are on your way to becoming a brilliant musician! The world of music is vast and there is still so much to learn so but I hope after finishing this course we have given you the elementary tools needed to listen out for and explore music.";
                Question question0=   new Question();
                question0.title = "What is the time signature of this piece?";
                question0.titleUrl = "icon_t9q1";
                question0.ansType="text";
                question0.a="3/4";
                question0.b="4/4";
                question0.ok="a";
                list.add(question0);
                Question question1=   new Question();
                question1.title = "Which is the correct rhythmic notation?";
                question1.ansType="image";
                question1.titleUrl="musict9q2";
                question1.a="icon20";
                question1.b="icon21";
                question1.ok="a";
                list.add(question1);
                Question question2=   new Question();
                question2.title = "Would you say the main melody of the piece is high or low in pitch?";
                question2.titleUrl = "e3nSvIiBNFo";
                question2.ansType="text";
                question2.a="High";
                question2.b="Low";
                question2.ok="a";
                list.add(question2);
                Question question3=   new Question();
                question3.title = "What is the time signature of the piece?";
                question3.titleUrl = "e3nSvIiBNFo";
                question3.ansType="text";
                question3.a="3/4";
                question3.b="4/4";
                question3.ok="b";
                list.add(question3);
                topic.mQuestions = list;
            }
            return topic;
        }
        return  null;
    }
}
